apiVersion: v1
kind: Service
metadata:
  name: {{ include "currencyservice.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "currencyservice.name" . }}
  ports:
  - name: grpc
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}

