replicaCount: 1

image:
  repository: loadgenerator
  tag: v0.10.4
  pullPolicy: IfNotPresent

busyboxImage: "busybox:latest"

env:
  frontend: "frontend:80"
  users: "10"
  rate: "1"

resources:
  requests:
    cpu: 300m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

