replicaCount: 1

image:
  repository: emailservice
  tag: v0.10.4
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000      # Service port
  targetPort: 8080   # Container port

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

