apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-cart.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "redis-cart.name" . }}
  ports:
  - name: tcp-redis
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}

